SESSIONS = [
    {
        "name": "Session A - 20 turn medium mixed flow",
        "queries": [
            "What is overfitting in machine learning?",
            "Give me a two-sentence version only.",
            "Can you explain that again in beginner language?",
            "Now compare overfitting and underfitting with one practical example each.",
            "Is dropout always guaranteed to improve test accuracy?",
            "Before answering, verify that claim carefully and include uncertainty.",
            "I need a step-by-step checklist to diagnose unstable validation loss.",
            "Do step 1 from your checklist now.",
            "Search for common causes of validation loss spikes after epoch 5.",
            "Synthesize the search findings and your checklist into one plan.",
            "I think your previous two answers conflict, resolve the contradiction.",
            "What should I do next right now, no fluff.",
            "I am confused by learning rate schedules; think through cosine vs step decay tradeoffs.",
            "Can you give me one short recommendation from that tradeoff?",
            "Could you clarify what assumptions you used in that recommendation?",
            "Now provide a full training plan for a small image classifier project from data prep to evaluation.",
            "Execute the data-prep phase only, with exact ordered tasks.",
            "Verify this statement: larger batch size always improves generalization.",
            "Merge everything so far into a compact action plan for the next 3 days.",
            "Final answer: one paragraph summary for a junior teammate.",
        ],
        "expected_actions": [
            "act_respond",
            "act_respond",
            "act_respond",
            "act_respond",
            "act_verify",
            "act_verify",
            "act_decompose",
            "act_respond",
            "act_search",
            "act_synthesize",
            "act_think",
            "act_respond",
            "act_think",
            "act_respond",
            "act_respond",
            "act_decompose",
            "act_decompose",
            "act_verify",
            "act_synthesize",
            "act_respond",
        ],
        "acceptable_actions": [
            ["act_think"],
            [],
            ["act_think"],
            ["act_think"],
            ["act_respond"],
            ["act_search"],
            ["act_think"],
            ["act_decompose"],
            ["act_verify"],
            ["act_think"],
            [],
            ["act_think"],
            ["act_synthesize"],
            ["act_think"],
            ["act_think"],
            ["act_think"],
            ["act_think"],
            ["act_search"],
            ["act_decompose"],
            ["act_synthesize"],
        ],
    },
    {
        "name": "Session B - 20 turn medium hardcore OOD research",
        "queries": [
            "I am building a neural registration study for OOD robustness across density, noise, and scale shifts. Create a phased research execution plan with decision gates.",
            "Execute phase 1 now with exact dataset generation procedure and split definitions.",
            "From your phase 1 output, decompose the annotation and quality-control pipeline.",
            "Think through likely hidden leakage paths between train and OOD validation splits.",
            "Search for source-backed practices to prevent leakage in synthetic geometric datasets.",
            "Synthesize those practices into a protocol I can enforce this week.",
            "Verify this claim: if OOD error is 2x in-distribution error, the model is overfitting by definition.",
            "Create an ablation matrix for encoder backbone, pooling, and loss weighting.",
            "Execute the backbone ablation design in concrete table-like bullets.",
            "Now compare mean pooling vs max pooling vs attention pooling for density invariance.",
            "Search for papers or reports that discuss pooling behavior under point-cloud density shift.",
            "Synthesize the evidence and choose one default pooling strategy plus caveat.",
            "I think your chosen pooling strategy conflicts with your earlier leakage concerns; resolve that contradiction.",
            "Decompose a two-week execution schedule with milestones and owners.",
            "Do milestone 1 only and provide exact artifacts to save.",
            "Verify this statement: adding more parameters alone prevents collapse in recursive self-training.",
            "Think through a minimal toy experiment that can falsify that statement.",
            "Search for collapse diagnostics that are practical for weekly monitoring.",
            "Merge toy experiment + diagnostics into one execution-ready test protocol.",
            "Final response: concise next-step recommendation for my team standup.",
        ],
        "expected_actions": [
            "act_decompose",
            "act_decompose",
            "act_decompose",
            "act_think",
            "act_search",
            "act_synthesize",
            "act_verify",
            "act_decompose",
            "act_decompose",
            "act_synthesize",
            "act_search",
            "act_synthesize",
            "act_think",
            "act_decompose",
            "act_decompose",
            "act_verify",
            "act_think",
            "act_search",
            "act_synthesize",
            "act_respond",
        ],
        "acceptable_actions": [
            ["act_think"],
            ["act_think"],
            ["act_think"],
            ["act_synthesize"],
            ["act_verify"],
            ["act_decompose"],
            ["act_search"],
            ["act_synthesize"],
            ["act_think"],
            ["act_think", "act_respond"],
            ["act_synthesize"],
            ["act_think"],
            [],
            ["act_synthesize"],
            ["act_think"],
            ["act_search"],
            ["act_decompose"],
            ["act_verify"],
            ["act_decompose"],
            ["act_think"],
        ],
    },
    {
        "name": "Session C - 20 turn medium hardcore multi-source benchmark",
        "queries": [
            "I need an end-to-end benchmark plan to compare MCMC and variational inference for hierarchical models under strict reproducibility constraints. Break it into phases.",
            "Execute phase 1 with exact model/task selection criteria.",
            "Now decompose evaluation metrics and diagnostics with pass/fail thresholds.",
            "Think through failure modes where VI appears good but uncertainty is miscalibrated.",
            "Search for source-backed comparisons of MCMC vs VI uncertainty quality.",
            "Synthesize those findings into one decision rubric.",
            "Verify this claim: VI always underestimates uncertainty and is therefore unsuitable for safety-critical settings.",
            "Create a week-by-week experimental rollout plan for this benchmark.",
            "Do week 1 tasks only with concrete outputs.",
            "Now I will give a follow-up: execute step 3 from your week 1 tasks and keep it practical.",
            "Search for reproducibility checklist standards that can be adapted to this benchmark.",
            "Synthesize checklist standards into a minimal compliance template.",
            "I think your compliance template conflicts with your earlier pass/fail thresholds; resolve explicitly.",
            "Clarify one missing project constraint you need before final lock-in.",
            "Given all prior context, provide a revised rollout with reduced compute budget.",
            "Verify this statement: fixed random seed alone is enough for reproducibility.",
            "Think through tradeoffs between strict reproducibility and rapid iteration speed.",
            "Search for practical logging fields that most improve reproducibility audits.",
            "Combine tradeoffs + logging + compliance template into one final benchmark governance plan.",
            "Final concise recommendation for leadership in one short paragraph.",
        ],
        "expected_actions": [
            "act_decompose",
            "act_decompose",
            "act_decompose",
            "act_think",
            "act_search",
            "act_synthesize",
            "act_verify",
            "act_decompose",
            "act_decompose",
            "act_respond",
            "act_search",
            "act_synthesize",
            "act_think",
            "act_clarify",
            "act_decompose",
            "act_verify",
            "act_think",
            "act_search",
            "act_synthesize",
            "act_respond",
        ],
        "acceptable_actions": [
            ["act_think"],
            ["act_respond"],
            ["act_think"],
            ["act_synthesize"],
            ["act_verify"],
            ["act_think"],
            ["act_search"],
            ["act_synthesize"],
            ["act_think"],
            ["act_decompose"],
            ["act_synthesize"],
            ["act_think"],
            ["act_verify"],
            [],
            [],
            ["act_search"],
            ["act_synthesize"],
            ["act_think"],
            ["act_decompose"],
            ["act_think"],
        ],
    },
]
