SESSIONS = [
    {
        "name": "Hardcore A - Neural ICP OOD Mission",
        "queries": [
            "I am designing a strict toy benchmark to test OOD generalization for neural point-cloud registration. Build a complete research plan with phases, dependencies, and deliverables.",
            "Execute phase 1 now: define the exact dataset generation protocol and split definitions for in-distribution, density-shift, scale-shift, and high-noise tests.",
            "Based on the protocol you just gave, synthesize the key failure modes that each split is expected to expose.",
            "Verify this claim with caveats: if model error on any OOD split is more than 2x the in-distribution baseline, that indicates structural overfitting.",
            "Now decompose an ablation matrix to isolate which architecture choices drive density invariance versus scale robustness.",
            "Given the ablation matrix, think through which ablation should be prioritized first under limited compute and explain why.",
            "Create a step-by-step execution checklist for the first two weeks of experiments.",
            "Compare your current checklist with your first research plan and synthesize one merged plan without redundancy.",
            "Do step 2 from the mergd plan now and show only evidence-style bullets.",
            "Give a concise final recommendation for the next immediate action with one caveat.",
        ],
        "expected_actions": [
            "act_decompose",
            "act_decompose",
            "act_synthesize",
            "act_verify",
            "act_decompose",
            "act_think",
            "act_decompose",
            "act_synthesize",
            "act_respond",
            "act_respond",
        ],
        "acceptable_actions": [
            ["act_think", "act_search"],
            ["act_search"],
            ["act_think", "act_search"],
            ["act_search"],
            ["act_synthesize"],
            ["act_synthesize"],
            ["act_search"],
            ["act_think"],
            ["act_decompose"],
            ["act_think"],
        ],
    },
    {
        "name": "Hardcore X - Almighty Research Router Sweep",
        "queries": [
            "I am preparing a high-stakes research program for OOD-robust geometric learning in robotics. Build a phased execution plan with decision gates, dependencies, and deliverables.",
            "Execute phase 1 now with concrete dataset protocol, split design, and artifact checklist.",
            "Given your phase 1 output, think through the two highest-risk failure modes and explain why they are most dangerous.",
            "Search for source-backed practices used to avoid data leakage and benchmark contamination in similar research settings.",
            "Synthesize your plan and the retrieved practices into one unified protocol that my team can follow.",
            "Verify this claim with confidence and caveats: if OOD error is above 2x IID error, the model is definitely overfitting.",
            "Do it now.",
            "In one clear paragraph, what is model collapse in recursive self-training?",
            "Given everything above, think through whether we should prioritize robustness gains or reproducibility hardening first under limited compute.",
            "Break that decision into a 7-day execution checklist with owners and measurable completion criteria.",
            "Search for practical weekly monitoring indicators that can warn us early about collapse or instability.",
            "Final output: give me the single most important next action in two short sentences.",
        ],
        "expected_actions": [
            "act_decompose",
            "act_decompose",
            "act_think",
            "act_search",
            "act_synthesize",
            "act_verify",
            "act_verify",
            "act_respond",
            "act_think",
            "act_decompose",
            "act_search",
            "act_respond",
        ],
        "acceptable_actions": [
            ["act_think", "act_search"],
            ["act_think"],
            ["act_synthesize"],
            ["act_verify"],
            ["act_think", "act_search"],
            ["act_search"],
            ["act_clarify"],
            ["act_think"],
            ["act_synthesize"],
            ["act_think"],
            ["act_verify"],
            ["act_think"],
        ],
    },
    {
        "name": "Hardcore X1 - Action Mini Search",
        "queries": [
            "Find 3 recent peer-reviewed sources on OOD robustness for geometric learning in robotics and cite them.",
            "Search for benchmark standards used to evaluate geometric OOD in point-cloud registration.",
            "Look up source-backed practices to prevent benchmark contamination in LLM-assisted research pipelines.",
            "Retrieve evidence comparing domain randomization versus adversarial perturbation for Sim2Real robustness.",
            "Search for practical indicators used in weekly monitoring of model collapse risk in recursive training.",
            "Find and summarize source-backed pros and cons of E(3)-equivariant models for noisy point-cloud settings.",
        ],
        "expected_actions": [
            "act_search",
            "act_search",
            "act_search",
            "act_search",
            "act_search",
            "act_search",
        ],
        "acceptable_actions": [
            ["act_verify", "act_synthesize"],
            ["act_verify", "act_synthesize"],
            ["act_verify", "act_synthesize"],
            ["act_verify", "act_synthesize"],
            ["act_verify", "act_synthesize"],
            ["act_verify", "act_synthesize"],
        ],
    },
    {
        "name": "Hardcore X2 - Action Mini Verify",
        "queries": [
            "Verify this claim with confidence and one caveat: doubling model size alone prevents recursive model collapse.",
            "Check whether this statement is true: OOD error above 2x IID error always means overfitting.",
            "Validate this claim: single-metric reporting is sufficient for OOD robustness evaluation.",
            "Verify whether this policy changed this week: benchmark leakage checks can rely on exact string matching only.",
            "Assess this statement with uncertainty: canary strings are a reliable detector of contamination in all setups.",
            "Verify if this claim is valid: deterministic seeds alone guarantee full reproducibility across different hardware.",
        ],
        "expected_actions": [
            "act_verify",
            "act_verify",
            "act_verify",
            "act_verify",
            "act_verify",
            "act_verify",
        ],
        "acceptable_actions": [
            ["act_search"],
            ["act_search"],
            ["act_search", "act_think"],
            ["act_search", "act_clarify"],
            ["act_search", "act_think"],
            ["act_search", "act_think"],
        ],
    },
    {
        "name": "Hardcore X3 - Action Mini Decompose",
        "queries": [
            "Create a phased research execution plan for OOD-robust geometric learning with deliverables, dependencies, and decision gates.",
            "Break this into a 14-day implementation roadmap with owners and measurable completion criteria.",
            "Decompose an ablation matrix to isolate effects of pooling, normalization, and noise schedules.",
            "Build a step-by-step protocol for dataset construction, split design, and artifact tracking.",
            "Split the deployment path into simulation, hardware-in-the-loop, and field validation stages with go/no-go checks.",
            "Produce an ordered checklist to move from toy benchmark to production-like benchmark with explicit checkpoints.",
        ],
        "expected_actions": [
            "act_decompose",
            "act_decompose",
            "act_decompose",
            "act_decompose",
            "act_decompose",
            "act_decompose",
        ],
        "acceptable_actions": [
            ["act_think"],
            ["act_think", "act_synthesize"],
            ["act_think"],
            ["act_think", "act_search"],
            ["act_think", "act_synthesize"],
            ["act_think"],
        ],
    },
    {
        "name": "Hardcore X4 - Action Mini Synthesize",
        "queries": [
            "Synthesize the planning guidance and evidence into one unified protocol the team can execute without redundancy.",
            "Combine the benchmark design notes and risk notes into one coherent policy with a single caveat.",
            "Merge conflicting recommendations about robustness versus reproducibility into one balanced decision memo.",
            "Integrate the retrieved findings into one concise strategy for weekly monitoring and intervention triggers.",
            "Synthesize the main agreements, key differences, and uncertainty from the evidence gathered so far.",
            "Create one final integrated recommendation that reconciles the tradeoffs across all prior outputs.",
        ],
        "expected_actions": [
            "act_synthesize",
            "act_synthesize",
            "act_synthesize",
            "act_synthesize",
            "act_synthesize",
            "act_synthesize",
        ],
        "acceptable_actions": [
            ["act_think"],
            ["act_think", "act_verify"],
            ["act_think", "act_verify"],
            ["act_think", "act_search"],
            ["act_think"],
            ["act_think"],
        ],
    },
    {
        "name": "Hardcore B - Unified EBM for VO-SLAM-VPR",
        "queries": [
            "I want one unified energy formulation for VO, SLAM, and visual place recognition with missing intrinsics and variable sequence length. Break this into an implementation roadmap.",
            "Implement roadmap step 1 conceptually: define the factorized energy terms and the variable sets for known versus latent parameters.",
            "Think through the tradeoffs between min-optimization proxy and marginalization approximations in this setting.",
            "Search for source-backed methods that handle latent pose/intrinsics in energy-based or probabilistic geometric models.",
            "Synthesize the retrieved ideas into one architecture recommendation with explicit assumptions.",
            "Verify this statement: additive energy decomposition is always stable under independent learned factors.",
            "Now decompose a training curriculum from easiest supervised regime to weakly supervised regime.",
            "Do step 3 from that curriculum now and provide concrete mini-experiment details.",
            "I think your previous recommendation was inconsistent; re-check and resolve the contradiction explicitly.",
            "Provide the final concise proposal that I can send to my team today.",
        ],
        "expected_actions": [
            "act_decompose",
            "act_think",
            "act_think",
            "act_search",
            "act_synthesize",
            "act_verify",
            "act_decompose",
            "act_decompose",
            "act_verify",
            "act_respond",
        ],
        "acceptable_actions": [
            ["act_think", "act_search"],
            ["act_search"],
            ["act_search"],
            ["act_verify"],
            ["act_think", "act_search"],
            ["act_search"],
            ["act_synthesize"],
            ["act_think", "act_respond"],
            ["act_think"],
            ["act_verify"],
        ],
    },
    {
        "name": "Hardcore C - Minimal Toy Prototype Build",
        "queries": [
            "Design a minimal but runnable toy prototype for translation-only point-cloud energy optimization to validate generalization assumptions. Give ordered implementation stages.",
            "Write the stage-by-stage coding plan with module boundaries, test hooks, and expected outputs.",
            "Now think through likely failure points in optimization dynamics before coding begins.",
            "Search for practical guidance on stabilizing contrastive EBM training with hard negatives.",
            "Synthesize a robust default training recipe from those findings.",
            "Verify whether this claim is reliable: max pooling in point encoders is sufficient for density invariance in all cases.",
            "Break down an ablation suite covering pooling, normalization, and noise schedules.",
            "Execute the first ablation design now in concrete terms: variables, fixed controls, and acceptance criteria.",
            "Can you clarify one missing detail you absolutely need before finalizing this prototype plan?",
            "Given the full conversation, provide final next-week tasks in strict execution order.",
        ],
        "expected_actions": [
            "act_decompose",
            "act_decompose",
            "act_think",
            "act_search",
            "act_synthesize",
            "act_verify",
            "act_decompose",
            "act_think",
            "act_clarify",
            "act_decompose",
        ],
        "acceptable_actions": [
            ["act_think", "act_search"],
            [],
            ["act_search", "act_decompose"],
            ["act_synthesize"],
            ["act_think"],
            ["act_search"],
            ["act_synthesize"],
            ["act_search", "act_decompose"],
            [],
            ["act_think"],
        ],
    },
    {
        "name": "Hardcore D - OOD Evaluation and Metrics",
        "queries": [
            "Create a rigorous evaluation protocol for OOD geometric registration including metrics, thresholds, and reporting templates.",
            "Do protocol step 1 now: define the exact primary and secondary metrics and why each is needed.",
            "Think about edge cases where Frobenius matrix error can hide failure and propose mitigation metrics.",
            "Search for benchmark reporting standards for OOD robustness in 3D registration and related geometric tasks.",
            "Synthesize one final reporting schema that is both strict and practical for weekly team reviews.",
            "Verify this claim: single-metric reporting is enough to judge OOD robustness for registration systems.",
            "Break down a reproducibility checklist for seeds, environment, and data generation determinism.",
            "Execute checklist item 2 now and write what exact artifacts must be stored.",
            "Given our prior outputs, compare two reporting schemas and choose one with justification.",
            "Give a concise final summary I can paste in project docs.",
        ],
        "expected_actions": [
            "act_decompose",
            "act_think",
            "act_think",
            "act_search",
            "act_synthesize",
            "act_verify",
            "act_decompose",
            "act_respond",
            "act_think",
            "act_respond",
        ],
        "acceptable_actions": [
            ["act_think"],
            ["act_search"],
            ["act_search"],
            ["act_synthesize"],
            ["act_think"],
            ["act_search"],
            [],
            ["act_decompose"],
            [],
            ["act_clarify"],
        ],
    },
    {
        "name": "Hardcore E - Contradiction and Claim Stress",
        "queries": [
            "I have two internal notes: one says larger models solve collapse, another says collapse persists. Decompose how to adjudicate this conflict empirically.",
            "Now execute the first adjudication step with concrete test design details.",
            "Search for source-backed evidence on whether scaling alone prevents collapse in recursive training.",
            "Synthesize the evidence into a position statement with explicit uncertainty.",
            "Verify this exact claim with confidence: increasing model size alone prevents collapse.",
            "I think your synthesis and verification conflict; resolve the contradiction explicitly.",
            "Create a short action plan to prevent this contradiction pattern in future reviews.",
            "Do step 1 from that action plan now.",
            "Can you tell me what to do next with no fluff?",
            "One-sentence final recommendation.",
        ],
        "expected_actions": [
            "act_decompose",
            "act_think",
            "act_search",
            "act_synthesize",
            "act_verify",
            "act_think",
            "act_decompose",
            "act_respond",
            "act_respond",
            "act_respond",
        ],
        "acceptable_actions": [
            ["act_synthesize", "act_think"],
            ["act_decompose"],
            ["act_synthesize"],
            ["act_think"],
            [],
            ["act_verify"],
            ["act_verify"],
            ["act_decompose"],
            [],
            ["act_think"],
        ],
    },
    {
        "name": "Hardcore F - Multi-source Research Flow",
        "queries": [
            "Plan a multi-source research workflow to evaluate robustness of energy-based geometric models across academic, engineering, and deployment perspectives.",
            "Execute the source-planning step now: what sources, in what order, and why.",
            "Search for recent technical discussions plus formal papers on EBM stability for geometric tasks.",
            "Synthesize the cross-source findings into one coherent set of design principles.",
            "Verify this statement: recommendations from community discussions align with peer-reviewed evidence in this area.",
            "Break down a decision rubric that maps evidence strength to implementation priority.",
            "Apply rubric step 2 to current findings and produce a ranked shortlist.",
            "Think through one high-risk decision in that shortlist and provide one caveat.",
            "Now produce an executive summary for technical leads and one for non-technical stakeholders.",
            "Can you clarify the single missing input that would most improve your ranking quality?",
        ],
        "expected_actions": [
            "act_decompose",
            "act_decompose",
            "act_search",
            "act_synthesize",
            "act_verify",
            "act_decompose",
            "act_think",
            "act_think",
            "act_respond",
            "act_clarify",
        ],
        "acceptable_actions": [
            ["act_search", "act_synthesize"],
            ["act_search"],
            ["act_synthesize"],
            ["act_search"],
            ["act_search"],
            ["act_think"],
            [],
            [],
            [],
            [],
        ],
    },
    {
        "name": "Hardcore G - Long Prompt Continuity",
        "queries": [
            "I will give you a long problem statement with constraints, risks, and goals. Build a phased research execution plan and identify decision gates at each phase.",
            "Use the same plan and now expand phase 1 into day-level tasks with expected artifacts.",
            "From what you already generated, do only the risk section and add measurable triggers.",
            "Now search for external evidence that supports or challenges those risk triggers.",
            "Synthesize those findings with our internal plan and update only the risk gates.",
            "Verify whether one of your updated risk gates is based on weak evidence.",
            "Given everything above, think through whether phase ordering should change.",
            "Apply your ordering change and output the new plan in numbered form.",
            "I think step 4 is unclear. Ask one clarifying question before proceeding.",
            "After clarification, provide final next three actions only.",
        ],
        "expected_actions": [
            "act_wait",
            "act_decompose",
            "act_decompose",
            "act_search",
            "act_synthesize",
            "act_verify",
            "act_think",
            "act_decompose",
            "act_clarify",
            "act_clarify",
        ],
        "acceptable_actions": [
            ["act_clarify"],
            ["act_think"],
            ["act_respond"],
            ["act_synthesize"],
            ["act_think"],
            ["act_search"],
            ["act_synthesize"],
            ["act_think"],
            [],
            ["act_wait"],
        ],
    },
    {
        "name": "Hardcore H - Research Assistant End-to-End",
        "queries": [
            "Act as a research copilot: decompose this full problem into hypotheses, methods, metrics, and release criteria.",
            "Run the hypotheses part now and make each hypothesis falsifiable.",
            "Search for strongest evidence patterns that would falsify each hypothesis.",
            "Synthesize evidence patterns into a practical test schedule.",
            "Verify if any hypothesis is currently untestable with our available data.",
            "Think through an alternative hypothesis family if that untestable one is dropped.",
            "Decompose a migration plan from toy benchmark to realistic production-like benchmark.",
            "Execute migration step 1 in detail.",
            "Now combine everything into one final research brief with caveats and action owners.",
            "Give the final brief in concise format suitable for a weekly meeting.",
        ],
        "expected_actions": [
            "act_decompose",
            "act_think",
            "act_search",
            "act_synthesize",
            "act_verify",
            "act_think",
            "act_decompose",
            "act_decompose",
            "act_synthesize",
            "act_respond",
        ],
        "acceptable_actions": [
            ["act_think"],
            [],
            ["act_synthesize"],
            ["act_think"],
            ["act_search"],
            ["act_decompose"],
            ["act_synthesize"],
            ["act_think"],
            ["act_think"],
            [],
        ],
    },
]
